<#
.SYNOPSIS
Regenerates web/mq_js_bundle.js from the JavaScript glue shipped inside the locked crates.

.DESCRIPTION
The WebAssembly build needs the JS halves of three crates, in the exact versions of Cargo.lock:

  miniquad      js/gl.js            loader, WebGL, input, plugin registry
  quad-snd      js/audio.js         macroquad audio ("macroquad_audio" plugin)
  sapp-jsutils  js/sapp_jsutils.js  JsObject support ("sapp_jsutils" plugin)

macroquad ships a prebuilt mq_js_bundle.js, but it wraps sapp_jsutils in a closure, so its
`js_object` / `consume_js_object` helpers are not reachable by other plugins such as
web/hero_web.js (and it bundles quad-net, which this game does not use). This script builds the
bundle from the crate sources instead: gl.js as is, audio.js in its own closure, and
sapp_jsutils.js in a closure that exports its object helpers on `window`.

Run it after upgrading macroquad / miniquad / quad-snd / sapp-jsutils; the file header records
the versions used. Needs `cargo` (reads the package locations from `cargo metadata`).
#>
$ErrorActionPreference = "Stop"
$Root = (Resolve-Path (Join-Path $PSScriptRoot "../..")).Path
Push-Location $Root
try {
    $json = & cargo metadata --format-version 1 --locked --filter-platform wasm32-unknown-unknown
    if ($LASTEXITCODE -ne 0) { throw "cargo metadata failed (exit code $LASTEXITCODE)" }
    $meta = $json | ConvertFrom-Json

    function Get-CrateJs([string]$crate, [string]$file) {
        $pkgs = @($meta.packages | Where-Object { $_.name -eq $crate })
        if ($pkgs.Count -ne 1) { throw "expected exactly one '$crate' package in the dependency graph, found $($pkgs.Count)" }
        $dir = Split-Path $pkgs[0].manifest_path
        $path = Join-Path $dir $file
        if (-not (Test-Path $path)) { throw "$path not found" }
        [pscustomobject]@{
            Label  = "$crate $($pkgs[0].version) $file"
            Source = (Get-Content -Raw $path) -replace "`r`n", "`n"
        }
    }

    $gl = Get-CrateJs "miniquad" "js/gl.js"
    $audio = Get-CrateJs "quad-snd" "js/audio.js"
    $jsutils = Get-CrateJs "sapp-jsutils" "js/sapp_jsutils.js"

    $out = [System.Text.StringBuilder]::new()
    [void]$out.Append("// mq_js_bundle.js for Eiketsuden Reloaded - generated by tools/web/update-js-bundle.ps1; do not edit.`n")
    [void]$out.Append("// Sources (MIT OR Apache-2.0, see the crates' licence files):`n")
    foreach ($part in @($gl, $audio, $jsutils)) {
        [void]$out.Append("//   $($part.Label)`n")
    }
    [void]$out.Append("`n// ----- $($gl.Label)`n")
    [void]$out.Append($gl.Source.TrimEnd())
    [void]$out.Append("`n`n// ----- $($audio.Label)`n(function () {`n")
    [void]$out.Append($audio.Source.TrimEnd())
    [void]$out.Append("`n}());`n`n// ----- $($jsutils.Label)`n(function () {`n")
    [void]$out.Append($jsutils.Source.TrimEnd())
    [void]$out.Append("`n// Eiketsuden: expose the JsObject helpers to other plugins (web/hero_web.js).`n")
    [void]$out.Append("window.js_object = js_object;`n")
    [void]$out.Append("window.consume_js_object = consume_js_object;`n")
    [void]$out.Append("window.get_js_object = get_js_object;`n")
    [void]$out.Append("}());`n")

    $target = Join-Path $Root "web/mq_js_bundle.js"
    [System.IO.File]::WriteAllText($target, $out.ToString(), [System.Text.UTF8Encoding]::new($false))
    Write-Host "wrote $target"
    foreach ($part in @($gl, $audio, $jsutils)) { Write-Host "  $($part.Label)" }
} finally {
    Pop-Location
}
